### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by denzillobo** [DeshdeepDivakar/Frameworks#1]
Hey Deshdeep
I am opening this sln file in Visual Studio community edition after downloading.
Unable to open due to incompatibility
How are you running this framework?
Is there something I am doing wrong?

**Comment by DeshdeepDivakar** [comment]
What is the full error message you are getting? It would be really helpful if you share that message.

**Comment by denzillobo** [comment]
![error opening on vs](https://cloud.githubusercontent.com/assets/21049904/17724978/23ba6fae-648a-11e6-92f3-0b500bd74c74.png)
![solutions explorer](https://cloud.githubusercontent.com/assets/21049904/17724995/4c5ae470-648a-11e6-931d-3aafe175aa72.png)

hope this helps mate

**Comment by DeshdeepDivakar** [comment]
What is the version of Visual studio you are using? 

Try this Delete folder ComponenModelCache

C:\Users\XXXX\AppData\Local\Microsoft\VisualStudio\XX\ComponentModelCache

**Comment by denzillobo** [comment]
I do not seem to have that folder on my machine Deshdeep

I am using Visual Studio 2015
![vs](https://cloud.githubusercontent.com/assets/21049904/17757599/5cef8128-652b-11e6-9d4a-7bb48961e11f.png)

**Comment by DeshdeepDivakar** [comment]
Hey could you please try to follow this link

http://stackoverflow.com/questions/17574089/microsoft-visual-studio-package-did-not-load-correctly/23159044

**Comment by AmitKulkarni9** [comment]
Denzil,

Just create a Project Solution in your VS and copy all the Deshdeep's projects .cs files to your Projects. I think this should resolve it ? 

Amit

**Comment by DeshdeepDivakar** [comment]
@AmitKulkarni9  You also had the same issue??

**Comment by AmitKulkarni9** [comment]
@DCube No, It worked for me.

**Comment by DeshdeepDivakar** [comment]
@denzillobo see if you could reinstall Visual Studio and download the project again. Give this a go and let me know if you still have this issue.

**Comment by denzillobo** [comment]
i have installed Atom and it opens correctly.
Thanks Amit and Deshdeep

@denzillobo Can you use Atom to build, Compile C# code??
